services:
  db:
    image: postgres:18.1
    container_name: booker-db

    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}
      PGDATA: /var/lib/postgresql/18/docker

    volumes:
      - db_data:/var/lib/postgresql

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 5

    networks:
      - booker-network

  migrations:
    image: flyway/flyway:11.17.2
    container_name: booker-migrations

    command: -url=jdbc:postgresql://db:5432/${SPRING_DATASOURCE_NAME} -user=${SPRING_DATASOURCE_USERNAME} -password=${SPRING_DATASOURCE_PASSWORD} -locations=filesystem:/flyway/migrations migrate

    volumes:
      - ./src/main/resources/db/migration:/flyway/migrations

    depends_on:
      db:
        condition: service_healthy

    networks:
      - booker-network

networks:
  booker-network:
    name: booker-network

volumes:
  db_data: