services:
  db:
    image: postgres:18.1
    container_name: booker-db

    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}
      PGDATA: /var/lib/postgresql/18/docker

    volumes:
      - db_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 5

    networks:
      - booker-network

  migrations:
    image: flyway/flyway:11.17.2
    container_name: booker-migrations

    command: -url=jdbc:postgresql://db:5432/${SPRING_DATASOURCE_NAME} -user=${SPRING_DATASOURCE_USERNAME} -password=${SPRING_DATASOURCE_PASSWORD} -locations=filesystem:/flyway/migrations migrate

    volumes:
      - ./src/main/resources/db/migration:/flyway/migrations

    depends_on:
      db:
        condition: service_healthy

    networks:
      - booker-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booker-api

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}
      SUPABASE_API_KEY: ${SUPABASE_API_KEY}
      STORAGE_BUCKET: ${STORAGE_BUCKET}

    ports:
      - "8080:8080"

    depends_on:
      migrations:
        condition: service_completed_successfully

    networks:
      - booker-network

networks:
  booker-network:
    driver: bridge

volumes:
  db_data: