services:
  db:
    image: postgres:17
    container_name: booker-db
    
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}

    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 5

  flyway:
    image: flyway/flyway:11.17.1
    container_name: flyway

    command: -url=jdbc:postgresql://db:5432/${SPRING_DATASOURCE_NAME} -user=${SPRING_DATASOURCE_USERNAME} -password=${SPRING_DATASOURCE_PASSWORD} -locations=filesystem:/flyway/migrations migrate

    volumes:
      - ./src/main/resources/db/migration:/flyway/migrations

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: