spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  application:
    name: booker

  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600000  # 1 hora em milisegundos
  refresh-token:
    expiration: 604800000  # 7 dias em milisegundos

# Configurações do Supabase Storage
supabase:
  project-id: ${SUPABASE_PROJECT_ID}
  api-key: ${SUPABASE_API_KEY}

storage:
  bucket: ${STORAGE_BUCKET}