spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  application:
    name: booker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

    hibernate:
      ddl-auto: validate

# Configurações do Supabase Storage
supabase:
  project-id: ${SUPABASE_PROJECT_ID}
  api-key: ${SUPABASE_API_KEY}

storage:
  bucket: ${STORAGE_BUCKET}