spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: booker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR

# Configurações do Supabase Storage
supabase:
  project-id: ${SUPABASE_PROJECT_ID}
  api-key: ${SUPABASE_API_KEY}

storage:
  bucket: ${STORAGE_BUCKET}